#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

log "---------- dev-env ----------"

find_dirs() {
    if [[ "$(uname)" == "Darwin" ]]; then
        dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
    else
        dirs=$(find . -mindepth 1 -maxdepth 1 -type d -printf "%P\n")
    fi
    echo $dirs
}

# Copies dir
# - `to` is forcefully removed!!!
# - `from` is copied over
copy_dir() {
    from=$1
    to=$2
    from_dir=$(dirname $from)
    from_name=$(basename $from)

    pushd $from_dir > /dev/null
    execute rm -rf $to
    execute cp -r $from_name $(dirname $to)/.
    popd > /dev/null
}

# Copies all subdirs
# - All subdirs in `to` are forcefully removed
# - All subdirs in `from` are copied over
copy_subdirs() {
    from=$1
    to=$2

    pushd $from > /dev/null
    dirs=$(find_dirs)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done
    popd > /dev/null
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)

    execute rm -f $to/$name
    execute cp -r $from $to/$name
}

# Symlinks dir
# - `to` is replaced with a symlink to `from` (absolute path)
# - If `to` already points at `from`, no-op
# - If `to` is a regular dir or a symlink elsewhere, it is removed first
link_dir() {
    from=$(cd "$1" && pwd)
    to=$2

    if [[ -L $to && "$(readlink $to)" == "$from" ]]; then
        log "link_dir $from -> $to (already linked)"
        return
    fi

    if [[ -L $to || -e $to ]]; then
        execute rm -rf $to
    fi
    execute ln -s $from $to
}

copy_file env/.zprofile ${HOME}
copy_file env/.ready-tmux ${HOME}
copy_file env/.bashrc ${HOME}
copy_file env/.bash_profile ${HOME}
copy_subdirs .local ${HOME}/.local

link_dir .config/nvim ${HOME}/.config/nvim
copy_dir .config/tmux ${HOME}/.config/tmux
if [[ "$(uname)" == "Linux" ]]; then
    if uname -a 2>/dev/null | grep -q "arch"; then
        copy_dir .config/hypr ${HOME}/.config/hypr
        execute hyprctl reload
    fi
fi

if [[ -d ${ZSH_CUSTOM} ]]; then
    copy_file env/oh-my-zsh.zsh ${ZSH_CUSTOM}
elif [[ -d ${HOME}/.oh-my-zsh/custom ]]; then
    copy_file env/oh-my-zsh.zsh ${HOME}/.oh-my-zsh/custom
else
    echo "No custom ZSH location. Skipping oh-my-zsh.zsh copy."
fi
