#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

log "---------- dev-env ----------"

find_dirs() {
    if [[ "$(uname)" == "Darwin" ]]; then
        dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
    else
        dirs=$(find . -mindepth 1 -maxdepth 1 -type d -printf "%P\n")
    fi
    echo $dirs
}

copy_dir() {
    from=$1
    to=$2

    pushd $from > /dev/null
    dirs=$(find_dirs)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done
    popd > /dev/null
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)

    execute rm -f $to/$name
    execute cp -r $from $to/$name
}

copy_dir .config ${HOME}/.config
copy_dir .local ${HOME}/.local
copy_file env/.zprofile ${HOME}
copy_file env/.ready-tmux ${HOME}

if [[ -d ${ZSH_CUSTOM} ]]; then
    copy_file env/oh-my-zsh.zsh ${ZSH_CUSTOM}
elif [[ -d ${HOME}/.oh-my-zsh/custom ]]; then
    copy_file env/oh-my-zsh.zsh ${HOME}/.oh-my-zsh/custom
else
    echo "No custom ZSH location. Skipping oh-my-zsh.zsh copy."
fi