#!/usr/bin/env bash

if [[ "$(uname)" == "Linux" ]]; then
  if uname -a 2>/dev/null | grep -q "arch"; then
    sudo pacman -S direnv
  else
    echo "This Linux distribution is not supported."
    exit 1
  fi
else
  echo "This OS is not supported."
fi
