#!/usr/bin/env bash

# Source: https://rakhesh.com/mac/using-hidutil-to-map-macos-keyboard-keys/
# Key table usages: https://developer.apple.com/library/archive/technotes/tn2450/_index.html#//apple_ref/doc/uid/DTS40017618-CH1-KEY_TABLE_USAGES
#
# Keyboard Escape: 0x29
# Keyboard Caps Lock: 0x39
hidutil property --set '{ "UserKeyMapping":[ { "HIDKeyboardModifierMappingSrc":0x700000029, "HIDKeyboardModifierMappingDst":0x700000039 }, { "HIDKeyboardModifierMappingSrc":0x700000039, "HIDKeyboardModifierMappingDst":0x700000029 } ] }'

