#!/usr/bin/env bash

if [[ "$(uname)" == "Linux" ]]; then
    if lsb_release -a 2>/dev/null | grep -q "Debian"; then
        sudo apt-get update && sudo apt-get install -y cmake gettext lua5.4-dev liblua5.4-dev
    else
        echo "This Linux distribution is not supported."
        exit 1
    fi
elif [[ "$(uname)" == "Darwin" ]]; then
    brew install cmake gettext lua@5.4
else
    echo "This OS is not supported."
fi

git clone -b v0.10.2 https://github.com/neovim/neovim.git ${HOME}/projects/neovim

cd ${HOME}/projects/neovim
make CMAKE_BUILD_TYPE="RelWithDebInfo"
sudo make install
